---
- name: "Run Docker-Compose using ansible playbook"
  hosts: localhost
  tasks:
  - name: stop and remove containers
    command: docker-compose down
    ignore_errors: yes

  # Make sure to change the image name with your personal dockerhub account and reposiroty 
  - name: remove image built with dockercompose
    command: docker rmi ahmedalaa14/laravel-app
    ignore_errors: yes

  - name: remove php-apache image
    command: docker rmi php:7.4.1-apache
    ignore_errors: yes

  - name: remove mysql image
    command: docker rmi mysql:5.7
    ignore_errors: yes

  - name: remove phpmyadmin image
    command: docker rmi phpmyadmin/phpmyadmin
    ignore_errors: yes

  - name: build docker-compose
    command: docker-compose up -d 

